services:
  mysql:
    image: mysql:8.4
    container_name: mysql_test
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      TZ: "Asia/Tokyo"
    volumes:
      - sql/init.sql:/docker-entrypoint-initdb.d/init.sql
